import re, sys
JS = "/work/1d8f9b53-fbd4-4904-b388-7257e3f8eb55/57e69dd7/workdir/js8call"
params = open(f"{JS}/lib/ft8/ldpc_174_87_params.f90").read()
bp = open(f"{JS}/lib/ft8/bpdecode174.f90").read()

def data_block(text, name):
    # returns the text between 'data NAME/' and the terminating '/'
    m = re.search(r"data\s+"+name+r"/(.*?)/\s*$", text, re.S | re.M)
    if not m:
        m = re.search(r"data\s+"+name+r"/(.*?)/", text, re.S)
    return m.group(1)

# generator hex strings
gblock = data_block(params, "g")
gen = re.findall(r'"([0-9a-fA-F]{22})"', gblock)
assert len(gen) == 87, len(gen)

# colorder (from params)
cblock = data_block(params, "colorder")
colorder = [int(x) for x in re.findall(r'-?\d+', cblock)]
assert len(colorder) == 174, len(colorder)

# Nm(7,87): from bpdecode174
nmblock = data_block(bp, "Nm")
nm = [int(x) for x in re.findall(r'-?\d+', nmblock)]
assert len(nm) == 7*87, len(nm)
nm_rows = [nm[i*7:(i+1)*7] for i in range(87)]

# Mn(3,174)
mnblock = data_block(bp, "Mn")
mn = [int(x) for x in re.findall(r'-?\d+', mnblock)]
assert len(mn) == 3*174, len(mn)
mn_rows = [mn[i*3:(i+1)*3] for i in range(174)]

# nrw(87)
nrwblock = data_block(bp, "nrw")
nrw = [int(x) for x in re.findall(r'-?\d+', nrwblock)]
assert len(nrw) == 87, len(nrw)

out = []
out.append("//! LDPC(174,87) tables for JS8, transcribed **verbatim** from the js8call")
out.append("//! reference (upstream `js8call/js8call` @ a7ff1be). Generated by")
out.append("//! `scratch/refvectors/js8/gen_js8_tables.py` — do not edit by hand.")
out.append("//!")
out.append("//! ref: lib/ft8/ldpc_174_87_params.f90 (`g`, `colorder`),")
out.append("//!      lib/ft8/bpdecode174.f90 (`Nm`, `Mn`, `nrw`).")
out.append("//!")
out.append("//! The (174,87) code is a regular column-weight-3 PEG LDPC. `encode174`")
out.append("//! forms `[parity(87) | message(87)]` then permutes columns by `COLORDER`;")
out.append("//! the parity-check Tanner graph (`NM`/`NRW`/`MN`) operates on that permuted")
out.append("//! codeword. All indices are kept in the reference's **1-origin** form and")
out.append("//! rebased to 0 at the point of use.")
out.append("")
out.append("/// Parity generator matrix rows: 87 rows of 22 hex chars (88 bits, first 87")
out.append("/// used). Row `i` gives the message-bit contributions to parity bit `i`.")
out.append("/// ref: ldpc_174_87_params.f90 `character*22 g(87)`.")
out.append("pub const JS8_174_87_GEN: [&str; 87] = [")
for g in gen:
    out.append(f'    "{g}",')
out.append("];")
out.append("")
out.append("/// Column reorder applied by `encode174` (`codeword(colorder+1)=itmp`).")
out.append("/// 0-origin codeword positions. ref: ldpc_174_87_params.f90 `colorder(174)`.")
out.append("pub const JS8_174_87_COLORDER: [usize; 174] = [")
for i in range(0, 174, 12):
    row = ", ".join(str(x) for x in colorder[i:i+12])
    out.append(f"    {row},")
out.append("];")
out.append("")
out.append("/// Tanner graph, checks → codeword bits: `NM[c]` lists the (1-origin)")
out.append("/// codeword indices in check `c`, zero-padded to 7; `NRW[c]` is the valid")
out.append("/// count (5, 6, or 7). ref: bpdecode174.f90 `Nm(7,87)` / `nrw(87)`.")
out.append("pub const JS8_174_87_NM: [[u8; 7]; 87] = [")
for r in nm_rows:
    out.append(f"    [{', '.join(str(x) for x in r)}],")
out.append("];")
out.append("")
out.append("/// Valid entries per check for [`JS8_174_87_NM`]. ref: bpdecode174.f90 `nrw`.")
out.append("pub const JS8_174_87_NRW: [u8; 87] = [")
for i in range(0, 87, 10):
    row = ", ".join(str(x) for x in nrw[i:i+10])
    out.append(f"    {row},")
out.append("];")
out.append("")
out.append("/// Tanner graph, bits → checks: `MN[v]` lists the 3 (1-origin) checks that")
out.append("/// include codeword bit `v` (column weight 3). ref: bpdecode174.f90 `Mn(3,174)`.")
out.append("pub const JS8_174_87_MN: [[u16; 3]; 174] = [")
for r in mn_rows:
    out.append(f"    [{', '.join(str(x) for x in r)}],")
out.append("];")
out.append("")

open("omnimodem/crates/dsp/src/fec/js8_tables.rs", "w").write("\n".join(out))
print("wrote js8_tables.rs:", len(gen), "gen rows,", len(colorder), "colorder,", len(nm_rows), "Nm,", len(mn_rows), "Mn,", len(nrw), "nrw")
