// Omnimodem control-plane API.
//
// Stability: package is versioned (omnimodem.v1). Within a major version,
// changes are ADDITIVE ONLY — see proto/VERSIONING.md. Field tags are never
// reused or renumbered.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: omnimodem.proto

package omnimodemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PttMethod int32

const (
	PttMethod_PTT_METHOD_UNSPECIFIED PttMethod = 0
	PttMethod_PTT_METHOD_NONE        PttMethod = 1
	PttMethod_PTT_METHOD_VOX         PttMethod = 2
	PttMethod_PTT_METHOD_SERIAL_RTS  PttMethod = 3
	PttMethod_PTT_METHOD_SERIAL_DTR  PttMethod = 4
	PttMethod_PTT_METHOD_CM108       PttMethod = 5
	PttMethod_PTT_METHOD_GPIO        PttMethod = 6
	PttMethod_PTT_METHOD_RIGCTLD     PttMethod = 7 // Hamlib rigctld over TCP (host:port in `node`)
	PttMethod_PTT_METHOD_ANDROID     PttMethod = 8 // actuated by the Android/Kotlin USB layer (method int in `pin_or_line`)
)

// Enum value maps for PttMethod.
var (
	PttMethod_name = map[int32]string{
		0: "PTT_METHOD_UNSPECIFIED",
		1: "PTT_METHOD_NONE",
		2: "PTT_METHOD_VOX",
		3: "PTT_METHOD_SERIAL_RTS",
		4: "PTT_METHOD_SERIAL_DTR",
		5: "PTT_METHOD_CM108",
		6: "PTT_METHOD_GPIO",
		7: "PTT_METHOD_RIGCTLD",
		8: "PTT_METHOD_ANDROID",
	}
	PttMethod_value = map[string]int32{
		"PTT_METHOD_UNSPECIFIED": 0,
		"PTT_METHOD_NONE":        1,
		"PTT_METHOD_VOX":         2,
		"PTT_METHOD_SERIAL_RTS":  3,
		"PTT_METHOD_SERIAL_DTR":  4,
		"PTT_METHOD_CM108":       5,
		"PTT_METHOD_GPIO":        6,
		"PTT_METHOD_RIGCTLD":     7,
		"PTT_METHOD_ANDROID":     8,
	}
)

func (x PttMethod) Enum() *PttMethod {
	p := new(PttMethod)
	*p = x
	return p
}

func (x PttMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PttMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_omnimodem_proto_enumTypes[0].Descriptor()
}

func (PttMethod) Type() protoreflect.EnumType {
	return &file_omnimodem_proto_enumTypes[0]
}

func (x PttMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PttMethod.Descriptor instead.
func (PttMethod) EnumDescriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{0}
}

type ConfigureChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"` // logical channel id; reused id updates in place
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`        // operator-facing label
	Mode    string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`        // Phase 1 placeholder, e.g. "none"
}

func (x *ConfigureChannelRequest) Reset() {
	*x = ConfigureChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureChannelRequest) ProtoMessage() {}

func (x *ConfigureChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureChannelRequest.ProtoReflect.Descriptor instead.
func (*ConfigureChannelRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureChannelRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigureChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigureChannelRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ConfigureChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *ConfigureChannelResponse) Reset() {
	*x = ConfigureChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureChannelResponse) ProtoMessage() {}

func (x *ConfigureChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureChannelResponse.ProtoReflect.Descriptor instead.
func (*ConfigureChannelResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureChannelResponse) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type GetStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{2}
}

type TransmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // opaque frame bytes; not interpreted in Phase 1
}

func (x *TransmitRequest) Reset() {
	*x = TransmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitRequest) ProtoMessage() {}

func (x *TransmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitRequest.ProtoReflect.Descriptor instead.
func (*TransmitRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{3}
}

func (x *TransmitRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransmitRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TransmitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransmitId uint64 `protobuf:"varint,1,opt,name=transmit_id,json=transmitId,proto3" json:"transmit_id,omitempty"` // monotonically increasing per process
}

func (x *TransmitResponse) Reset() {
	*x = TransmitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitResponse) ProtoMessage() {}

func (x *TransmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitResponse.ProtoReflect.Descriptor instead.
func (*TransmitResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{4}
}

func (x *TransmitResponse) GetTransmitId() uint64 {
	if x != nil {
		return x.TransmitId
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{5}
}

type ModemState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*ChannelInfo `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
}

func (x *ModemState) Reset() {
	*x = ModemState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState) ProtoMessage() {}

func (x *ModemState) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState.ProtoReflect.Descriptor instead.
func (*ModemState) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{6}
}

func (x *ModemState) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ChannelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel  uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode     string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // stable device identity (placeholder in Phase 1)
	Running  bool   `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelInfo) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ChannelInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ChannelInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*Event_Snapshot
	//	*Event_ChannelConfigured
	//	*Event_TransmitStarted
	//	*Event_TransmitComplete
	//	*Event_RxFrame
	//	*Event_AudioLevel
	//	*Event_Status
	//	*Event_DeviceArrived
	//	*Event_DeviceDeparted
	//	*Event_PttState
	Kind isEvent_Kind `protobuf_oneof:"kind"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{8}
}

func (m *Event) GetKind() isEvent_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Event) GetSnapshot() *ModemState {
	if x, ok := x.GetKind().(*Event_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *Event) GetChannelConfigured() *ChannelConfigured {
	if x, ok := x.GetKind().(*Event_ChannelConfigured); ok {
		return x.ChannelConfigured
	}
	return nil
}

func (x *Event) GetTransmitStarted() *TransmitStarted {
	if x, ok := x.GetKind().(*Event_TransmitStarted); ok {
		return x.TransmitStarted
	}
	return nil
}

func (x *Event) GetTransmitComplete() *TransmitComplete {
	if x, ok := x.GetKind().(*Event_TransmitComplete); ok {
		return x.TransmitComplete
	}
	return nil
}

func (x *Event) GetRxFrame() *RxFrame {
	if x, ok := x.GetKind().(*Event_RxFrame); ok {
		return x.RxFrame
	}
	return nil
}

func (x *Event) GetAudioLevel() *AudioLevel {
	if x, ok := x.GetKind().(*Event_AudioLevel); ok {
		return x.AudioLevel
	}
	return nil
}

func (x *Event) GetStatus() *Status {
	if x, ok := x.GetKind().(*Event_Status); ok {
		return x.Status
	}
	return nil
}

func (x *Event) GetDeviceArrived() *DeviceArrived {
	if x, ok := x.GetKind().(*Event_DeviceArrived); ok {
		return x.DeviceArrived
	}
	return nil
}

func (x *Event) GetDeviceDeparted() *DeviceDeparted {
	if x, ok := x.GetKind().(*Event_DeviceDeparted); ok {
		return x.DeviceDeparted
	}
	return nil
}

func (x *Event) GetPttState() *PttState {
	if x, ok := x.GetKind().(*Event_PttState); ok {
		return x.PttState
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Snapshot struct {
	Snapshot *ModemState `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // always first on a fresh subscription
}

type Event_ChannelConfigured struct {
	ChannelConfigured *ChannelConfigured `protobuf:"bytes,2,opt,name=channel_configured,json=channelConfigured,proto3,oneof"`
}

type Event_TransmitStarted struct {
	TransmitStarted *TransmitStarted `protobuf:"bytes,3,opt,name=transmit_started,json=transmitStarted,proto3,oneof"`
}

type Event_TransmitComplete struct {
	TransmitComplete *TransmitComplete `protobuf:"bytes,4,opt,name=transmit_complete,json=transmitComplete,proto3,oneof"`
}

type Event_RxFrame struct {
	RxFrame *RxFrame `protobuf:"bytes,5,opt,name=rx_frame,json=rxFrame,proto3,oneof"` // LOSSLESS class
}

type Event_AudioLevel struct {
	AudioLevel *AudioLevel `protobuf:"bytes,6,opt,name=audio_level,json=audioLevel,proto3,oneof"` // LOSSY class
}

type Event_Status struct {
	Status *Status `protobuf:"bytes,7,opt,name=status,proto3,oneof"` // LOSSY class
}

type Event_DeviceArrived struct {
	DeviceArrived *DeviceArrived `protobuf:"bytes,8,opt,name=device_arrived,json=deviceArrived,proto3,oneof"` // LOSSY
}

type Event_DeviceDeparted struct {
	DeviceDeparted *DeviceDeparted `protobuf:"bytes,9,opt,name=device_departed,json=deviceDeparted,proto3,oneof"` // LOSSY
}

type Event_PttState struct {
	PttState *PttState `protobuf:"bytes,10,opt,name=ptt_state,json=pttState,proto3,oneof"` // LOSSY
}

func (*Event_Snapshot) isEvent_Kind() {}

func (*Event_ChannelConfigured) isEvent_Kind() {}

func (*Event_TransmitStarted) isEvent_Kind() {}

func (*Event_TransmitComplete) isEvent_Kind() {}

func (*Event_RxFrame) isEvent_Kind() {}

func (*Event_AudioLevel) isEvent_Kind() {}

func (*Event_Status) isEvent_Kind() {}

func (*Event_DeviceArrived) isEvent_Kind() {}

func (*Event_DeviceDeparted) isEvent_Kind() {}

func (*Event_PttState) isEvent_Kind() {}

type ChannelConfigured struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *ChannelConfigured) Reset() {
	*x = ChannelConfigured{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelConfigured) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfigured) ProtoMessage() {}

func (x *ChannelConfigured) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfigured.ProtoReflect.Descriptor instead.
func (*ChannelConfigured) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelConfigured) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type TransmitStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel    uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	TransmitId uint64 `protobuf:"varint,2,opt,name=transmit_id,json=transmitId,proto3" json:"transmit_id,omitempty"`
}

func (x *TransmitStarted) Reset() {
	*x = TransmitStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransmitStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitStarted) ProtoMessage() {}

func (x *TransmitStarted) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitStarted.ProtoReflect.Descriptor instead.
func (*TransmitStarted) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{10}
}

func (x *TransmitStarted) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransmitStarted) GetTransmitId() uint64 {
	if x != nil {
		return x.TransmitId
	}
	return 0
}

type TransmitComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel    uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	TransmitId uint64 `protobuf:"varint,2,opt,name=transmit_id,json=transmitId,proto3" json:"transmit_id,omitempty"`
}

func (x *TransmitComplete) Reset() {
	*x = TransmitComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransmitComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitComplete) ProtoMessage() {}

func (x *TransmitComplete) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitComplete.ProtoReflect.Descriptor instead.
func (*TransmitComplete) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{11}
}

func (x *TransmitComplete) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TransmitComplete) GetTransmitId() uint64 {
	if x != nil {
		return x.TransmitId
	}
	return 0
}

// A decoded RX frame. No DSP exists in Phase 1, so this is emitted only by
// tests/tools; it is defined now to pin the LOSSLESS backpressure contract.
type RxFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel     uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Data        []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TimestampNs uint64 `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
}

func (x *RxFrame) Reset() {
	*x = RxFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RxFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RxFrame) ProtoMessage() {}

func (x *RxFrame) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RxFrame.ProtoReflect.Descriptor instead.
func (*RxFrame) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{12}
}

func (x *RxFrame) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *RxFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RxFrame) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type AudioLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Dbfs    float32 `protobuf:"fixed32,2,opt,name=dbfs,proto3" json:"dbfs,omitempty"`
}

func (x *AudioLevel) Reset() {
	*x = AudioLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioLevel) ProtoMessage() {}

func (x *AudioLevel) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioLevel.ProtoReflect.Descriptor instead.
func (*AudioLevel) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{13}
}

func (x *AudioLevel) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *AudioLevel) GetDbfs() float32 {
	if x != nil {
		return x.Dbfs
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel  uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	TxFrames uint64 `protobuf:"varint,2,opt,name=tx_frames,json=txFrames,proto3" json:"tx_frames,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{14}
}

func (x *Status) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Status) GetTxFrames() uint64 {
	if x != nil {
		return x.TxFrames
	}
	return 0
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{15}
}

type DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // canonical DeviceId string (see ids.rs)
	Label       string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                       // operator-facing name
	HasCapture  bool   `protobuf:"varint,3,opt,name=has_capture,json=hasCapture,proto3" json:"has_capture,omitempty"`
	HasPlayback bool   `protobuf:"varint,4,opt,name=has_playback,json=hasPlayback,proto3" json:"has_playback,omitempty"`
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{16}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DeviceInfo) GetHasCapture() bool {
	if x != nil {
		return x.HasCapture
	}
	return false
}

func (x *DeviceInfo) GetHasPlayback() bool {
	if x != nil {
		return x.HasPlayback
	}
	return false
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*DeviceInfo `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{17}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ConfigureAudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel    uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // stable DeviceId; config keys on this
	SampleRate uint32 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // requested working rate (clamped to 48 kHz)
	Fanout     uint32 `protobuf:"varint,4,opt,name=fanout,proto3" json:"fanout,omitempty"`                           // capture consumers; 0/1 == no fan-out
}

func (x *ConfigureAudioRequest) Reset() {
	*x = ConfigureAudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureAudioRequest) ProtoMessage() {}

func (x *ConfigureAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureAudioRequest.ProtoReflect.Descriptor instead.
func (*ConfigureAudioRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigureAudioRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigureAudioRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConfigureAudioRequest) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *ConfigureAudioRequest) GetFanout() uint32 {
	if x != nil {
		return x.Fanout
	}
	return 0
}

type ConfigureAudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActualSampleRate uint32 `protobuf:"varint,1,opt,name=actual_sample_rate,json=actualSampleRate,proto3" json:"actual_sample_rate,omitempty"` // rate the stream actually opened at
}

func (x *ConfigureAudioResponse) Reset() {
	*x = ConfigureAudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureAudioResponse) ProtoMessage() {}

func (x *ConfigureAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureAudioResponse.ProtoReflect.Descriptor instead.
func (*ConfigureAudioResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigureAudioResponse) GetActualSampleRate() uint32 {
	if x != nil {
		return x.ActualSampleRate
	}
	return 0
}

type ConfigurePttRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel   uint32    `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	DeviceId  string    `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // stable DeviceId for the PTT device
	Method    PttMethod `protobuf:"varint,3,opt,name=method,proto3,enum=omnimodem.v1.PttMethod" json:"method,omitempty"`
	Node      string    `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`                               // resolved node / chip path (serial/cm108/gpio)
	PinOrLine uint32    `protobuf:"varint,5,opt,name=pin_or_line,json=pinOrLine,proto3" json:"pin_or_line,omitempty"` // cm108 GPIO pin (1-8) or gpiochip line offset
	Invert    bool      `protobuf:"varint,6,opt,name=invert,proto3" json:"invert,omitempty"`
}

func (x *ConfigurePttRequest) Reset() {
	*x = ConfigurePttRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurePttRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePttRequest) ProtoMessage() {}

func (x *ConfigurePttRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurePttRequest.ProtoReflect.Descriptor instead.
func (*ConfigurePttRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigurePttRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ConfigurePttRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConfigurePttRequest) GetMethod() PttMethod {
	if x != nil {
		return x.Method
	}
	return PttMethod_PTT_METHOD_UNSPECIFIED
}

func (x *ConfigurePttRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ConfigurePttRequest) GetPinOrLine() uint32 {
	if x != nil {
		return x.PinOrLine
	}
	return 0
}

func (x *ConfigurePttRequest) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

type ConfigurePttResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigurePttResponse) Reset() {
	*x = ConfigurePttResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigurePttResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurePttResponse) ProtoMessage() {}

func (x *ConfigurePttResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurePttResponse.ProtoReflect.Descriptor instead.
func (*ConfigurePttResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{21}
}

type KeyPttRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Keyed   bool   `protobuf:"varint,2,opt,name=keyed,proto3" json:"keyed,omitempty"` // true=key, false=unkey
}

func (x *KeyPttRequest) Reset() {
	*x = KeyPttRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPttRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPttRequest) ProtoMessage() {}

func (x *KeyPttRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPttRequest.ProtoReflect.Descriptor instead.
func (*KeyPttRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{22}
}

func (x *KeyPttRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *KeyPttRequest) GetKeyed() bool {
	if x != nil {
		return x.Keyed
	}
	return false
}

type KeyPttResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeyPttResponse) Reset() {
	*x = KeyPttResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPttResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPttResponse) ProtoMessage() {}

func (x *KeyPttResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPttResponse.ProtoReflect.Descriptor instead.
func (*KeyPttResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{23}
}

type SuggestUdevRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *SuggestUdevRuleRequest) Reset() {
	*x = SuggestUdevRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestUdevRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestUdevRuleRequest) ProtoMessage() {}

func (x *SuggestUdevRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestUdevRuleRequest.ProtoReflect.Descriptor instead.
func (*SuggestUdevRuleRequest) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{24}
}

func (x *SuggestUdevRuleRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type SuggestUdevRuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rule         string `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`                 // udev rule text
	Instructions string `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"` // where to put it
}

func (x *SuggestUdevRuleResponse) Reset() {
	*x = SuggestUdevRuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestUdevRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestUdevRuleResponse) ProtoMessage() {}

func (x *SuggestUdevRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestUdevRuleResponse.ProtoReflect.Descriptor instead.
func (*SuggestUdevRuleResponse) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{25}
}

func (x *SuggestUdevRuleResponse) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *SuggestUdevRuleResponse) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type DeviceArrived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Label    string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *DeviceArrived) Reset() {
	*x = DeviceArrived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceArrived) ProtoMessage() {}

func (x *DeviceArrived) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceArrived.ProtoReflect.Descriptor instead.
func (*DeviceArrived) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{26}
}

func (x *DeviceArrived) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceArrived) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DeviceDeparted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (x *DeviceDeparted) Reset() {
	*x = DeviceDeparted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceDeparted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDeparted) ProtoMessage() {}

func (x *DeviceDeparted) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDeparted.ProtoReflect.Descriptor instead.
func (*DeviceDeparted) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{27}
}

func (x *DeviceDeparted) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type PttState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel uint32 `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Keyed   bool   `protobuf:"varint,2,opt,name=keyed,proto3" json:"keyed,omitempty"`
}

func (x *PttState) Reset() {
	*x = PttState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omnimodem_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PttState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PttState) ProtoMessage() {}

func (x *PttState) ProtoReflect() protoreflect.Message {
	mi := &file_omnimodem_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PttState.ProtoReflect.Descriptor instead.
func (*PttState) Descriptor() ([]byte, []int) {
	return file_omnimodem_proto_rawDescGZIP(), []int{28}
}

func (x *PttState) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PttState) GetKeyed() bool {
	if x != nil {
		return x.Keyed
	}
	return false
}

var File_omnimodem_proto protoreflect.FileDescriptor

var file_omnimodem_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x22,
	0x5b, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x18,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x33, 0x0a, 0x10,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x49,
	0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x65, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0b, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x22, 0x9b, 0x05, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a,
	0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x50, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x11, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x12, 0x4a, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6d, 0x69, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x12, 0x4d, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x5f,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00,
	0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x72, 0x78, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x78, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x72,
	0x78, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6d,
	0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x44, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x72,
	0x72, 0x69, 0x76, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x6d,
	0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x47, 0x0a, 0x0f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x35, 0x0a, 0x09, 0x70, 0x74, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x74, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x08, 0x70, 0x74, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x22, 0x4c, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x22, 0x4d,
	0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x22, 0x5a, 0x0a,
	0x07, 0x52, 0x78, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x5f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4e, 0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x62, 0x66, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x64, 0x62, 0x66, 0x73, 0x22, 0x3f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x78, 0x5f,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x78,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x83, 0x01, 0x0a,
	0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x61, 0x63, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x62, 0x61,
	0x63, 0x6b, 0x22, 0x49, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6d, 0x6e,
	0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x87, 0x01,
	0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22,
	0xc9, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50, 0x74, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x2f,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x74,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x70, 0x69, 0x6e, 0x5f, 0x6f, 0x72, 0x5f, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x69, 0x6e, 0x4f, 0x72, 0x4c,
	0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x50, 0x74, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x6b, 0x65, 0x79, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6b,
	0x65, 0x79, 0x65, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x50, 0x74, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x0a, 0x16, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73,
	0x74, 0x55, 0x64, 0x65, 0x76, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x17, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x55, 0x64, 0x65, 0x76, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x42, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x72, 0x69, 0x76, 0x65,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x22, 0x2d, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x08, 0x50, 0x74, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x65, 0x79,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x65, 0x64, 0x2a,
	0xe1, 0x01, 0x0a, 0x09, 0x50, 0x74, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a,
	0x16, 0x50, 0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x54, 0x54,
	0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x50, 0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x56, 0x4f, 0x58,
	0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44,
	0x5f, 0x53, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x5f, 0x52, 0x54, 0x53, 0x10, 0x03, 0x12, 0x19, 0x0a,
	0x15, 0x50, 0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x53, 0x45, 0x52, 0x49,
	0x41, 0x4c, 0x5f, 0x44, 0x54, 0x52, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x54, 0x54, 0x5f,
	0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x43, 0x4d, 0x31, 0x30, 0x38, 0x10, 0x05, 0x12, 0x13,
	0x0a, 0x0f, 0x50, 0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x47, 0x50, 0x49,
	0x4f, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f,
	0x44, 0x5f, 0x52, 0x49, 0x47, 0x43, 0x54, 0x4c, 0x44, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x50,
	0x54, 0x54, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49,
	0x44, 0x10, 0x08, 0x32, 0xf8, 0x05, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6d, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x12, 0x61, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d,
	0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x08,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d,
	0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f,
	0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x6f, 0x6d, 0x6e,
	0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6f, 0x6d, 0x6e,
	0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30,
	0x01, 0x12, 0x52, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x12, 0x20, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x23, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f,
	0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f,
	0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50,
	0x74, 0x74, 0x12, 0x21, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50, 0x74, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x50, 0x74,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x4b, 0x65, 0x79,
	0x50, 0x74, 0x74, 0x12, 0x1b, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x74, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x4b, 0x65, 0x79, 0x50, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e,
	0x0a, 0x0f, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x55, 0x64, 0x65, 0x76, 0x52, 0x75, 0x6c,
	0x65, 0x12, 0x24, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x55, 0x64, 0x65, 0x76, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x6d, 0x6e, 0x69, 0x6d, 0x6f,
	0x64, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x55, 0x64,
	0x65, 0x76, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_omnimodem_proto_rawDescOnce sync.Once
	file_omnimodem_proto_rawDescData = file_omnimodem_proto_rawDesc
)

func file_omnimodem_proto_rawDescGZIP() []byte {
	file_omnimodem_proto_rawDescOnce.Do(func() {
		file_omnimodem_proto_rawDescData = protoimpl.X.CompressGZIP(file_omnimodem_proto_rawDescData)
	})
	return file_omnimodem_proto_rawDescData
}

var file_omnimodem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_omnimodem_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_omnimodem_proto_goTypes = []any{
	(PttMethod)(0),                   // 0: omnimodem.v1.PttMethod
	(*ConfigureChannelRequest)(nil),  // 1: omnimodem.v1.ConfigureChannelRequest
	(*ConfigureChannelResponse)(nil), // 2: omnimodem.v1.ConfigureChannelResponse
	(*GetStateRequest)(nil),          // 3: omnimodem.v1.GetStateRequest
	(*TransmitRequest)(nil),          // 4: omnimodem.v1.TransmitRequest
	(*TransmitResponse)(nil),         // 5: omnimodem.v1.TransmitResponse
	(*SubscribeRequest)(nil),         // 6: omnimodem.v1.SubscribeRequest
	(*ModemState)(nil),               // 7: omnimodem.v1.ModemState
	(*ChannelInfo)(nil),              // 8: omnimodem.v1.ChannelInfo
	(*Event)(nil),                    // 9: omnimodem.v1.Event
	(*ChannelConfigured)(nil),        // 10: omnimodem.v1.ChannelConfigured
	(*TransmitStarted)(nil),          // 11: omnimodem.v1.TransmitStarted
	(*TransmitComplete)(nil),         // 12: omnimodem.v1.TransmitComplete
	(*RxFrame)(nil),                  // 13: omnimodem.v1.RxFrame
	(*AudioLevel)(nil),               // 14: omnimodem.v1.AudioLevel
	(*Status)(nil),                   // 15: omnimodem.v1.Status
	(*ListDevicesRequest)(nil),       // 16: omnimodem.v1.ListDevicesRequest
	(*DeviceInfo)(nil),               // 17: omnimodem.v1.DeviceInfo
	(*ListDevicesResponse)(nil),      // 18: omnimodem.v1.ListDevicesResponse
	(*ConfigureAudioRequest)(nil),    // 19: omnimodem.v1.ConfigureAudioRequest
	(*ConfigureAudioResponse)(nil),   // 20: omnimodem.v1.ConfigureAudioResponse
	(*ConfigurePttRequest)(nil),      // 21: omnimodem.v1.ConfigurePttRequest
	(*ConfigurePttResponse)(nil),     // 22: omnimodem.v1.ConfigurePttResponse
	(*KeyPttRequest)(nil),            // 23: omnimodem.v1.KeyPttRequest
	(*KeyPttResponse)(nil),           // 24: omnimodem.v1.KeyPttResponse
	(*SuggestUdevRuleRequest)(nil),   // 25: omnimodem.v1.SuggestUdevRuleRequest
	(*SuggestUdevRuleResponse)(nil),  // 26: omnimodem.v1.SuggestUdevRuleResponse
	(*DeviceArrived)(nil),            // 27: omnimodem.v1.DeviceArrived
	(*DeviceDeparted)(nil),           // 28: omnimodem.v1.DeviceDeparted
	(*PttState)(nil),                 // 29: omnimodem.v1.PttState
}
var file_omnimodem_proto_depIdxs = []int32{
	8,  // 0: omnimodem.v1.ModemState.channels:type_name -> omnimodem.v1.ChannelInfo
	7,  // 1: omnimodem.v1.Event.snapshot:type_name -> omnimodem.v1.ModemState
	10, // 2: omnimodem.v1.Event.channel_configured:type_name -> omnimodem.v1.ChannelConfigured
	11, // 3: omnimodem.v1.Event.transmit_started:type_name -> omnimodem.v1.TransmitStarted
	12, // 4: omnimodem.v1.Event.transmit_complete:type_name -> omnimodem.v1.TransmitComplete
	13, // 5: omnimodem.v1.Event.rx_frame:type_name -> omnimodem.v1.RxFrame
	14, // 6: omnimodem.v1.Event.audio_level:type_name -> omnimodem.v1.AudioLevel
	15, // 7: omnimodem.v1.Event.status:type_name -> omnimodem.v1.Status
	27, // 8: omnimodem.v1.Event.device_arrived:type_name -> omnimodem.v1.DeviceArrived
	28, // 9: omnimodem.v1.Event.device_departed:type_name -> omnimodem.v1.DeviceDeparted
	29, // 10: omnimodem.v1.Event.ptt_state:type_name -> omnimodem.v1.PttState
	17, // 11: omnimodem.v1.ListDevicesResponse.devices:type_name -> omnimodem.v1.DeviceInfo
	0,  // 12: omnimodem.v1.ConfigurePttRequest.method:type_name -> omnimodem.v1.PttMethod
	1,  // 13: omnimodem.v1.ModemControl.ConfigureChannel:input_type -> omnimodem.v1.ConfigureChannelRequest
	3,  // 14: omnimodem.v1.ModemControl.GetState:input_type -> omnimodem.v1.GetStateRequest
	4,  // 15: omnimodem.v1.ModemControl.Transmit:input_type -> omnimodem.v1.TransmitRequest
	6,  // 16: omnimodem.v1.ModemControl.SubscribeEvents:input_type -> omnimodem.v1.SubscribeRequest
	16, // 17: omnimodem.v1.ModemControl.ListDevices:input_type -> omnimodem.v1.ListDevicesRequest
	19, // 18: omnimodem.v1.ModemControl.ConfigureAudio:input_type -> omnimodem.v1.ConfigureAudioRequest
	21, // 19: omnimodem.v1.ModemControl.ConfigurePtt:input_type -> omnimodem.v1.ConfigurePttRequest
	23, // 20: omnimodem.v1.ModemControl.KeyPtt:input_type -> omnimodem.v1.KeyPttRequest
	25, // 21: omnimodem.v1.ModemControl.SuggestUdevRule:input_type -> omnimodem.v1.SuggestUdevRuleRequest
	2,  // 22: omnimodem.v1.ModemControl.ConfigureChannel:output_type -> omnimodem.v1.ConfigureChannelResponse
	7,  // 23: omnimodem.v1.ModemControl.GetState:output_type -> omnimodem.v1.ModemState
	5,  // 24: omnimodem.v1.ModemControl.Transmit:output_type -> omnimodem.v1.TransmitResponse
	9,  // 25: omnimodem.v1.ModemControl.SubscribeEvents:output_type -> omnimodem.v1.Event
	18, // 26: omnimodem.v1.ModemControl.ListDevices:output_type -> omnimodem.v1.ListDevicesResponse
	20, // 27: omnimodem.v1.ModemControl.ConfigureAudio:output_type -> omnimodem.v1.ConfigureAudioResponse
	22, // 28: omnimodem.v1.ModemControl.ConfigurePtt:output_type -> omnimodem.v1.ConfigurePttResponse
	24, // 29: omnimodem.v1.ModemControl.KeyPtt:output_type -> omnimodem.v1.KeyPttResponse
	26, // 30: omnimodem.v1.ModemControl.SuggestUdevRule:output_type -> omnimodem.v1.SuggestUdevRuleResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_omnimodem_proto_init() }
func file_omnimodem_proto_init() {
	if File_omnimodem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_omnimodem_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TransmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TransmitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ModemState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelConfigured); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TransmitStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*TransmitComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RxFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*AudioLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ListDevicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ListDevicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureAudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureAudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigurePttRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigurePttResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*KeyPttRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*KeyPttResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*SuggestUdevRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*SuggestUdevRuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*DeviceArrived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*DeviceDeparted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omnimodem_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*PttState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_omnimodem_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_Snapshot)(nil),
		(*Event_ChannelConfigured)(nil),
		(*Event_TransmitStarted)(nil),
		(*Event_TransmitComplete)(nil),
		(*Event_RxFrame)(nil),
		(*Event_AudioLevel)(nil),
		(*Event_Status)(nil),
		(*Event_DeviceArrived)(nil),
		(*Event_DeviceDeparted)(nil),
		(*Event_PttState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_omnimodem_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omnimodem_proto_goTypes,
		DependencyIndexes: file_omnimodem_proto_depIdxs,
		EnumInfos:         file_omnimodem_proto_enumTypes,
		MessageInfos:      file_omnimodem_proto_msgTypes,
	}.Build()
	File_omnimodem_proto = out.File
	file_omnimodem_proto_rawDesc = nil
	file_omnimodem_proto_goTypes = nil
	file_omnimodem_proto_depIdxs = nil
}
