// Omnimodem control-plane API.
//
// Stability: package is versioned (omnimodem.v1). Within a major version,
// changes are ADDITIVE ONLY — see proto/VERSIONING.md. Field tags are never
// reused or renumbered.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: omnimodem.proto

package omnimodemv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModemControl_ConfigureChannel_FullMethodName = "/omnimodem.v1.ModemControl/ConfigureChannel"
	ModemControl_GetState_FullMethodName         = "/omnimodem.v1.ModemControl/GetState"
	ModemControl_Transmit_FullMethodName         = "/omnimodem.v1.ModemControl/Transmit"
	ModemControl_SubscribeEvents_FullMethodName  = "/omnimodem.v1.ModemControl/SubscribeEvents"
	ModemControl_ListDevices_FullMethodName      = "/omnimodem.v1.ModemControl/ListDevices"
	ModemControl_ConfigureAudio_FullMethodName   = "/omnimodem.v1.ModemControl/ConfigureAudio"
	ModemControl_ConfigurePtt_FullMethodName     = "/omnimodem.v1.ModemControl/ConfigurePtt"
	ModemControl_KeyPtt_FullMethodName           = "/omnimodem.v1.ModemControl/KeyPtt"
	ModemControl_SuggestUdevRule_FullMethodName  = "/omnimodem.v1.ModemControl/SuggestUdevRule"
)

// ModemControlClient is the client API for ModemControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Command-and-control plane for the Omnimodem software modem.
type ModemControlClient interface {
	// Create or update a virtual channel. Idempotent on channel id.
	ConfigureChannel(ctx context.Context, in *ConfigureChannelRequest, opts ...grpc.CallOption) (*ConfigureChannelResponse, error)
	// Snapshot the current modem state (channels + status).
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*ModemState, error)
	// Enqueue a frame for transmission on a channel. In Phase 1 this is
	// simulated: the core acknowledges with a transmit id and emits
	// TransmitStarted/TransmitComplete events. Returns once the frame is
	// accepted onto the channel's TX queue, not when it leaves the air.
	Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*TransmitResponse, error)
	// Subscribe to the event stream. The first message is always a snapshot
	// (Event.snapshot) reflecting state at subscription time; live events follow.
	SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Enumerate present audio/PTT-capable devices with their stable DeviceId.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// Bind a channel's audio to a device (by stable DeviceId) and open streams.
	ConfigureAudio(ctx context.Context, in *ConfigureAudioRequest, opts ...grpc.CallOption) (*ConfigureAudioResponse, error)
	// Bind a channel's PTT to a device + method.
	ConfigurePtt(ctx context.Context, in *ConfigurePttRequest, opts ...grpc.CallOption) (*ConfigurePttResponse, error)
	// Manually key/unkey a channel's PTT (operator test; no audio).
	KeyPtt(ctx context.Context, in *KeyPttRequest, opts ...grpc.CallOption) (*KeyPttResponse, error)
	// Return ready-to-install udev rule text for a device (never writes it).
	SuggestUdevRule(ctx context.Context, in *SuggestUdevRuleRequest, opts ...grpc.CallOption) (*SuggestUdevRuleResponse, error)
}

type modemControlClient struct {
	cc grpc.ClientConnInterface
}

func NewModemControlClient(cc grpc.ClientConnInterface) ModemControlClient {
	return &modemControlClient{cc}
}

func (c *modemControlClient) ConfigureChannel(ctx context.Context, in *ConfigureChannelRequest, opts ...grpc.CallOption) (*ConfigureChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureChannelResponse)
	err := c.cc.Invoke(ctx, ModemControl_ConfigureChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*ModemState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModemState)
	err := c.cc.Invoke(ctx, ModemControl_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) Transmit(ctx context.Context, in *TransmitRequest, opts ...grpc.CallOption) (*TransmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransmitResponse)
	err := c.cc.Invoke(ctx, ModemControl_Transmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModemControl_ServiceDesc.Streams[0], ModemControl_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModemControl_SubscribeEventsClient = grpc.ServerStreamingClient[Event]

func (c *modemControlClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, ModemControl_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) ConfigureAudio(ctx context.Context, in *ConfigureAudioRequest, opts ...grpc.CallOption) (*ConfigureAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureAudioResponse)
	err := c.cc.Invoke(ctx, ModemControl_ConfigureAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) ConfigurePtt(ctx context.Context, in *ConfigurePttRequest, opts ...grpc.CallOption) (*ConfigurePttResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurePttResponse)
	err := c.cc.Invoke(ctx, ModemControl_ConfigurePtt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) KeyPtt(ctx context.Context, in *KeyPttRequest, opts ...grpc.CallOption) (*KeyPttResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyPttResponse)
	err := c.cc.Invoke(ctx, ModemControl_KeyPtt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modemControlClient) SuggestUdevRule(ctx context.Context, in *SuggestUdevRuleRequest, opts ...grpc.CallOption) (*SuggestUdevRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestUdevRuleResponse)
	err := c.cc.Invoke(ctx, ModemControl_SuggestUdevRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModemControlServer is the server API for ModemControl service.
// All implementations must embed UnimplementedModemControlServer
// for forward compatibility.
//
// Command-and-control plane for the Omnimodem software modem.
type ModemControlServer interface {
	// Create or update a virtual channel. Idempotent on channel id.
	ConfigureChannel(context.Context, *ConfigureChannelRequest) (*ConfigureChannelResponse, error)
	// Snapshot the current modem state (channels + status).
	GetState(context.Context, *GetStateRequest) (*ModemState, error)
	// Enqueue a frame for transmission on a channel. In Phase 1 this is
	// simulated: the core acknowledges with a transmit id and emits
	// TransmitStarted/TransmitComplete events. Returns once the frame is
	// accepted onto the channel's TX queue, not when it leaves the air.
	Transmit(context.Context, *TransmitRequest) (*TransmitResponse, error)
	// Subscribe to the event stream. The first message is always a snapshot
	// (Event.snapshot) reflecting state at subscription time; live events follow.
	SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// Enumerate present audio/PTT-capable devices with their stable DeviceId.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// Bind a channel's audio to a device (by stable DeviceId) and open streams.
	ConfigureAudio(context.Context, *ConfigureAudioRequest) (*ConfigureAudioResponse, error)
	// Bind a channel's PTT to a device + method.
	ConfigurePtt(context.Context, *ConfigurePttRequest) (*ConfigurePttResponse, error)
	// Manually key/unkey a channel's PTT (operator test; no audio).
	KeyPtt(context.Context, *KeyPttRequest) (*KeyPttResponse, error)
	// Return ready-to-install udev rule text for a device (never writes it).
	SuggestUdevRule(context.Context, *SuggestUdevRuleRequest) (*SuggestUdevRuleResponse, error)
	mustEmbedUnimplementedModemControlServer()
}

// UnimplementedModemControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModemControlServer struct{}

func (UnimplementedModemControlServer) ConfigureChannel(context.Context, *ConfigureChannelRequest) (*ConfigureChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureChannel not implemented")
}
func (UnimplementedModemControlServer) GetState(context.Context, *GetStateRequest) (*ModemState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedModemControlServer) Transmit(context.Context, *TransmitRequest) (*TransmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transmit not implemented")
}
func (UnimplementedModemControlServer) SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedModemControlServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedModemControlServer) ConfigureAudio(context.Context, *ConfigureAudioRequest) (*ConfigureAudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureAudio not implemented")
}
func (UnimplementedModemControlServer) ConfigurePtt(context.Context, *ConfigurePttRequest) (*ConfigurePttResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigurePtt not implemented")
}
func (UnimplementedModemControlServer) KeyPtt(context.Context, *KeyPttRequest) (*KeyPttResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyPtt not implemented")
}
func (UnimplementedModemControlServer) SuggestUdevRule(context.Context, *SuggestUdevRuleRequest) (*SuggestUdevRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestUdevRule not implemented")
}
func (UnimplementedModemControlServer) mustEmbedUnimplementedModemControlServer() {}
func (UnimplementedModemControlServer) testEmbeddedByValue()                      {}

// UnsafeModemControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModemControlServer will
// result in compilation errors.
type UnsafeModemControlServer interface {
	mustEmbedUnimplementedModemControlServer()
}

func RegisterModemControlServer(s grpc.ServiceRegistrar, srv ModemControlServer) {
	// If the following call pancis, it indicates UnimplementedModemControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModemControl_ServiceDesc, srv)
}

func _ModemControl_ConfigureChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).ConfigureChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_ConfigureChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).ConfigureChannel(ctx, req.(*ConfigureChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_Transmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).Transmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_Transmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).Transmit(ctx, req.(*TransmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModemControlServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModemControl_SubscribeEventsServer = grpc.ServerStreamingServer[Event]

func _ModemControl_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_ConfigureAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).ConfigureAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_ConfigureAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).ConfigureAudio(ctx, req.(*ConfigureAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_ConfigurePtt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurePttRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).ConfigurePtt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_ConfigurePtt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).ConfigurePtt(ctx, req.(*ConfigurePttRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_KeyPtt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPttRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).KeyPtt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_KeyPtt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).KeyPtt(ctx, req.(*KeyPttRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModemControl_SuggestUdevRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestUdevRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModemControlServer).SuggestUdevRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModemControl_SuggestUdevRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModemControlServer).SuggestUdevRule(ctx, req.(*SuggestUdevRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModemControl_ServiceDesc is the grpc.ServiceDesc for ModemControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModemControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnimodem.v1.ModemControl",
	HandlerType: (*ModemControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureChannel",
			Handler:    _ModemControl_ConfigureChannel_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ModemControl_GetState_Handler,
		},
		{
			MethodName: "Transmit",
			Handler:    _ModemControl_Transmit_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _ModemControl_ListDevices_Handler,
		},
		{
			MethodName: "ConfigureAudio",
			Handler:    _ModemControl_ConfigureAudio_Handler,
		},
		{
			MethodName: "ConfigurePtt",
			Handler:    _ModemControl_ConfigurePtt_Handler,
		},
		{
			MethodName: "KeyPtt",
			Handler:    _ModemControl_KeyPtt_Handler,
		},
		{
			MethodName: "SuggestUdevRule",
			Handler:    _ModemControl_SuggestUdevRule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _ModemControl_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "omnimodem.proto",
}
